<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| If this is not set then CodeIgniter will guess the protocol, domain and
| path to your installation.
|
*/



/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'AUTO' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'AUTO'			Default - auto detects
| 'PATH_INFO'		Uses the PATH_INFO
| 'QUERY_STRING'	Uses the QUERY_STRING
| 'REQUEST_URI'		Uses the REQUEST_URI
| 'ORIG_PATH_INFO'	Uses the ORIG_PATH_INFO
|
*/
//$config['uri_protocol']	= 'ORIG_PATH_INFO';
if (isset($_SERVER['ORIG_PATH_INFO'])) {
	$_SERVER['PATH_INFO'] = $_SERVER['ORIG_PATH_INFO'];
}
$config['uri_protocol']	= 'PATH_INFO';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/urls.html
*/

$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'english';
$config['mia_system_multi_language'] = TRUE; //多国语言开关
/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = FALSE;


/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/core_classes.html
| http://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';


/*
 |--------------------------------------------------------------------------
 | Composer auto-loading
 |--------------------------------------------------------------------------
 |
 | Enabling this setting will tell CodeIgniter to look for a Composer
 | package auto-loader script in application/vendor/autoload.php.
 |
 |	$config['composer_autoload'] = TRUE;
 |
 | Or if you have your vendor/ directory located somewhere else, you
 | can opt to set a specific path as well:
 |
 |	$config['composer_autoload'] = '/path/to/vendor/autoload.php';
 |
 | For more information about Composer, please visit http://getcomposer.org/
 |
 | Note: This will NOT disable or override the CodeIgniter-specific
 |	autoloading (application/config/autoload.php)
 */
$config['composer_autoload'] = TRUE;

/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify with a regular expression which characters are permitted
| within your URLs.  When someone tries to submit a URL with disallowed
| characters they will get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';


/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['allow_get_array']		= TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger']	= 'c';
$config['function_trigger']		= 'm';
$config['directory_trigger']	= 'd'; // experimental not currently in use

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| If you have enabled error logging, you can set an error threshold to
| determine what gets logged. Threshold options are:
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 1;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ folder. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/cache/ folder.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class or the Session class you
| MUST set an encryption key.  See the user guide for info.
|
*/
$config['encryption_key'] = 'icat';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_cookie_name'		= the name you want for the cookie
| 'sess_expiration'			= the number of SECONDS you want the session to last.
|   by default sessions last 7200 seconds (two hours).  Set to zero for no expiration.
| 'sess_expire_on_close'	= Whether to cause the session to expire automatically
|   when the browser window is closed
| 'sess_encrypt_cookie'		= Whether to encrypt the cookie
| 'sess_use_database'		= Whether to save the session data to a database
| 'sess_table_name'			= The name of the session database table
| 'sess_match_ip'			= Whether to match the user's IP address when reading the session data
| 'sess_match_useragent'	= Whether to match the User Agent when reading the session data
| 'sess_time_to_update'		= how many seconds between CI refreshing Session Information
|
*/
/*
$config['sess_driver'] = 'database';
$config['sess_save_path'] = 'cat_session';
$config['sess_cookie_name']		= 'cat_session';
$config['sess_expiration']		= 7200;
$config['sess_use_database']	= TRUE;
$config['sess_table_name']		= 'cat_session';
$config['sess_match_ip']		= FALSE;
$config['sess_time_to_update']	= 7200;
*/
$config['sess_driver'] = 'redis';
$config['sess_save_path'] = 'tcp://10.0.0.8:6379?auth=PW';
#$config['sess_save_path'] = 'tcp://127.0.0.1:6379';
/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix' = Set a prefix if you need to avoid collisions
| 'cookie_domain' = Set to .your-domain.com for site-wide cookies
| 'cookie_path'   =  Typically will be a forward slash
| 'cookie_secure' =  Cookies will only be set if a secure HTTPS connection exists.
|
*/
$config['cookie_prefix']	= "";
$config['cookie_domain']	= "";
$config['cookie_path']		= "/";
$config['cookie_secure']	= FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
*/
$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or 'gmt'.  This pref tells the system whether to use
| your server's local time as the master 'now' reference, or convert it to
| GMT.  See the 'date helper' page of the user guide for information
| regarding date handling.
|
*/
$config['time_reference'] = 'local';


/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your  files.  Options are TRUE or FALSE (boolean)
|
*/
$config['rewrite_short_tags'] = FALSE;


/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy IP
| addresses from which CodeIgniter should trust the HTTP_X_FORWARDED_FOR
| header in order to properly identify the visitor's IP address.
| Comma-delimited, e.g. '10.0.1.200,10.0.1.201'
|
*/
$config['proxy_ips'] = '';

// DST的国家  0:US  1:Gemany
$config['dst_country'] = 0;

//代码类型  NP100:1 , NP200:2, All:3
$config['mia_system_set'] = 2;   //代码类型设置
$config['mia_system_np100'] = 1;
$config['mia_system_np200'] = 2;
$config['mia_system_all'] = 3;

//服务器地址设置
$config['mia_server_ip'] = '64.57.81.124';

//bandwidth
$config['bandwidth_open'] = FALSE;
$config['auto-register_open'] = TRUE;
$config['text.font_family'] = FALSE;
$config['covert.office.files'] = TRUE;

//company
$config['default.storage'] = '500MB'; //500MB

//page config
$config['page_default_size'] = 20;
$config['page_log_size'] = 20;
$config['page_group_size'] = 8;
$config['page_player_size'] = 20;
$config['page_media_size'] = 12;
$config['page_template_size'] = 6;
$config['page_template_image_size'] = 8;

$config['base_path'] = str_replace("\\", "/", realpath('.'));
$config['resources'] = './resources/';
if (!is_dir($config['resources'])) {
	mkdir($config['resources'], 777, TRUE);
}
$config['images'] = './images/';
$config['gz_path'] = '/home/miatek/np200/'; //终端压缩包下载目录
//system media lib path
$config['system_media_path'] = $config['resources'] . 'system/';

//campaign/ path
$config['playlist_publish_path'] = $config['resources'] . 'publish/';

//YUV path
$config['yuv_publish_path'] = $config['resources'] . 'publish/';

//temp cached file
$config['cached_temp_path'] = $config['resources'] . 'cached/';

//error log file
$config['cached_errorlog_path'] = $config['resources'] . 'errorlog/';

//tmp upload file path
$config['tmp'] = $config['base_path'] . '/upload/tmp';
if (!is_dir($config['tmp'])) {
	mkdir($config['tmp'], 777, TRUE);
}
$config['max_filesize'] = 524288000; //500MB

//rss
$config['rss_cache_path'] = './cached/';
$config['rss_cache_prefix'] = 'rsscache_';


//RSS格式设置 title only 
$config['rss_format_title'] = 0;
$config['rss_format_desc'] = 1;
$config['rss_format_all'] = 2;

//server timezone setting
$now = time();
$gmt = mktime(gmdate("H", $now), gmdate("i", $now), gmdate("s", $now), gmdate("m", $now), gmdate("d", $now), gmdate("Y", $now));
$config['server.timezone'] = ($now - $gmt) / 3600;
$config['server.dst'] = date('I') ? TRUE : FALSE;


$config['default_passd'] = '123456';

//$config['base_path']=str_replace("\\", "/", realpath('.'));

$config['ffmpeg'] = '/usr/bin/ffmpeg';
//auth config
$config['auth_view'] = 0; //group viewer
$config['auth_franchise'] = 1; //Franchise
$config['auth_group'] = 3; //group onwer
$config['auth_staff'] = 4;
$config['auth_admin'] = 5; //admin
$config['auth_system'] = 10; //system


$config['system_users'] = array('admin', 'administrator', 'system');

//media config
$config['media_type_image'] = 1;
$config['media_type_video'] = 2;
$config['media_type_rss'] = 3;
$config['media_type_music'] = 4;
$config['media_type_webpage'] = 5;


$config['media_source_local'] = 0;
$config['media_source_ftp'] = 1;
$config['media_source_http'] = 2;

$config['media_layout_grid'] = 0;
$config['media_layout_list'] = 1;
//preview status
$config['media_preview_disable'] = 0;
$config['media_preview_enable_main'] = 1;
$config['media_preview_enable_tiny'] = 2;


$config['image_max_size'] = 533504000; //5MB
$config['image_max_width'] = 0; //no limit
$config['image_max_height'] = 0; //no limit
$config['logo_max_size'] = 2048 * 1024 * 5; //2MB
$config['logo_max_width'] = 240; //no limit
$config['logo_max_height'] = 90; //no limit

$config['image_types'] = 'jpg|jpeg';
$config['image_tiny_width'] = 320;
$config['image_tiny_height'] = 180;
$config['image_main_width'] = 1280;
$config['image_main_height'] = 720;

//flash config
$config['image_file_types'] = '*.jpg;*.jpeg;*.bmp;*.png;';
$config['image_file_types_desc'] = 'Images File';

$config['video_file_types'] = '*.mpeg;*.mpg;*.mkv;*.mp4;*.divx;*.mov;*.avi;*.flv;*.wmv;';


$config['video_file_types_desc'] = 'Video File';

$config['music_file_types'] = '*.mp3;';
$config['music_file_types_desc'] = 'Music File';

//video config
$config['video_types'] = 'mpeg|avi';
//$config['video_max_size']=104857600;//100MB
$config['video_max_size'] = 524288000; //500MB

//ftp
$config['ftp_default_port'] = 21;
$config['ftp_limit'] = 10;


//template config
$config['template_user'] = 0;
$config['template_system'] = 1;
$config['template_size_1280_720'] = array('w' => 480, 'h' => 270);
$config['template_size_720_1280'] = array('w' => 270, 'h' => 480);
$config['template_size_1920_1080'] = array('w' => 960, 'h' => 540);
$config['template_size_1080_1920'] = array('w' => 540, 'h' => 960);

//temolate limit
$config['template_limit'] = 10;

//screen size info
$config['screen_width'] = 640;
$config['screen_height'] = 360;

//预览图大小
$config['template_preview_width'] = 480;
$config['template_preview_reverse_width'] = 152;
$config['template_preview_height'] = 270;

$config['tempate_preview_path'] = '/resources/preview/%d/template';
$config['playlist_preview_path'] = '/resources/preview/%d/campaign/';

//area config

$config['area_type_movie'] = 0;
$config['area_type_image'] = 1;
$config['area_type_image2'] = 3;
$config['area_type_image3'] = 4;
$config['area_type_text'] = 2;
$config['area_type_date'] = 3;
$config['area_type_time'] = 4;
$config['area_type_weather'] = 5;
$config['area_type_logo'] = 8;
$config['area_type_bg']   = 9;
$config['area_type_webpage'] = 7;
$config['area_type_mask'] = 28;
$config['area_type_staticText'] = 18;
$config['area_type_btn'] = 25;

//transmode type
//视频全屏
$config['transmode_type_full'] = 1;
//视频分屏
$config['transmode_type_part'] = 2;
//照片区域
$config['transmode_type_image'] = 3;

//bg color
$config['area_type_movie_color'] = '#336b96';
$config['area_type_image_color'] = '#ffff00';
$config['area_type_image1_color'] = '#95b555';
$config['area_type_image2_color'] = '#5a974b';
$config['area_type_image3_color'] = '#378c6d';
$config['area_type_image4_color'] = '#528B8B';
$config['area_type_text_color'] = '#679fca';
$config['area_type_staticText_color'] = '#7171C6';
$config['area_type_date_color'] = '#5f698c';
$config['area_type_time_color'] = '#4876FF';
$config['area_type_weather_color'] = '#4d7ea3';
$config['area_type_logo_color'] = '#7EC0EE';
$config['area_type_webpage_color'] = '#0072E3';
$config['area_type_btnGroup_color'] = '#EBEBEB';
$config['area_type_btn_color'] = '#74afe4';
$config['area_type_mask_color'] = '#ffcc00';

$config['area_border_color'] = '#CCCCCC';
//area media flag
$config['area_media_flag_temp'] = 0;
$config['area_media_flag_ok'] = 1;
$config['area_media_flag_delete'] = 2;
$config['area_media_flag_all'] = array(0, 1, 2);


$config['area_media_size'] = 8;

//时间对应php格式转化
$config['area_date_format_0'] = 'Y/m/d';
$config['area_date_format_1'] = 'Y-m-d';
$config['area_date_format_1'] = 'm/d/Y';

$config['area_time_format_0'] = 'H:i:s';
$config['area_time_format_1'] = 'H:i';

//area text setting
//$config['area_text_speed']=

//campaign/
$config['playlist_type_normal'] = 0;          //播放列表
$config['playlist_type_instant_program'] = 1; //即时节目
$config['playlist_type_instant_text']   = 2; //即时字幕

$config['playlist.status.default'] = 0;
$config['playlist.status.published'] = 1;

$config['media.transmode.mapping'] = array(23, 6, 7, 5, 4, 13, 14, 15, 16, 8, 9, 1, 0, 25, 26, 17, 19, 18, 20, 27, 28, 29, 30, 10, 22, 21, 31, 24);

//schedule
$config['schedule.default'] = 0;
$config['schedule.publish'] = 1;

$config['schedule.day'] = 'agendaDay';
$config['schedule.week'] = 'agendaWeek';
$config['schedule.month'] = 'month';
$config['schedule.default_event_minutes'] = 120;

$config['oneday'] = 24 * 60 * 60;

//客户端离线判断时间，单位分钟
$config['player.offline.limit'] = 11;
$config['player.model.0'] = 'VGA';
$config['player.model.1'] = 'HDMI_50';
$config['player.model.2'] = 'HDMI_60';

//客户机事件状态
$config['event_type_login'] = 1;
$config['event_type_heartbeat'] = 2;
$config['event_type_download'] = 3;
$config['event_type_playback'] = 4;
$config['event_type_time'] = 5;


$config['accesslog'] = TRUE;

//Email Settings

$config['email.from_name'] = 'miatek';
$config['email.from_mail'] = 'support@miatek.com';
$config['email.smtp_server'] = 'smtp.exmail.qq.com';
$config['email.smtp_port'] = 465;
$config['email.reply_to'] = 'support@miatek.com';
$config['email.password'] = 'Tc44584';



if (isset($_SERVER['HTTP_HOST'])) {
	$config['base_url']   = '//' . $_SERVER['HTTP_HOST'] . '/';
} else {
	$config['base_url'] = 'http://icat6.local';
}
$config['area_video'] = 101;
$config['area_pic1'] = 102;
$config['area_pic2'] = 103;
$config['area_pic2'] = 104;
$config['area_pic2'] = 105;


$config['new_offline_email'] = TRUE;
$config['xml_news_support'] = TRUE;
$config['player_capcity'] = TRUE;
$config['xslot_on'] = TRUE;
$config['cost_entry'] = TRUE;
$config['player_pics'] = TRUE;

$config['news_duration'] = 10;
$config['cam_with_player'] = TRUE;

$config['has_weather'] = TRUE;

$config['with_sub_folders'] = TRUE;
$config['digooh_timer_per_hour'] = TRUE;

$config['campaign_with_tags'] = TRUE;
$config['tcp_port'] = 4702;
$config['allowed_video_types'] = array("avi", "mp4", "divx", 'mpeg', 'mpg', 'mkv', 'mov');
$config['allowed_image_types'] = array('gif', 'png', 'jpg', 'jpeg');

$config['with_partners'] = true;
$config['ssp_feature'] = true;
/* End of file config.php */
/* Location: ./application/config/config.php */
